name:                princesa
version:             0.1.0.0
github:              "githubuser/princesa"
license:             BSD3
author:              "Franco Testagrossa"
maintainer:          "franco.testagrossa@gmail.com"
copyright:           "2020 Franco Testagrossa here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/princesa#readme>

dependencies:
- base >= 4.7 && < 5
# json serializer
- aeson
# http server
- servant
- servant-server
- wai
- warp
# repository
- persistent
- persistent-postgresql
- persistent-template
# logger
- monad-logger
- fast-logger
- katip
- wai-extra
# reader-t
- mtl
# bytestring
- bytestring
# safe
- safe
# text
- text
# cli
- optparse-generic

library:
  source-dirs: src
  exposed-modules:
    Lib
    Application.Mode
    Application.Cli
    Application.App
    Infrastructure.Http.Api
    Infrastructure.Persistence.DBRuntime
    Infrastructure.Environment
    Infrastructure.Config
    Infrastructure.Logger
    Infrastructure.System
    Infrastructure.Types
  other-modules:
    Modules.Candidates.Domain.Entity
    Modules.Candidates.Domain.Service
    Modules.Candidates.Domain.Repository
    Modules.Candidates.Infrastructure.Http.Api
    Modules.Candidates.Infrastructure.Http.Handler
    Modules.Candidates.Infrastructure.Persistence.Db
    Modules.Candidates.Infrastructure.Persistence.Models
    Modules.Candidates.Infrastructure.Json.Marshaller
    Modules.Jobs.Domain.Entity
    Modules.Jobs.Domain.Service
    Modules.Jobs.Domain.Repository
    Modules.Jobs.Infrastructure.Http.Api
    Modules.Jobs.Infrastructure.Http.Handler
    Modules.Jobs.Infrastructure.Persistence.Db
    Modules.Jobs.Infrastructure.Persistence.Models
    Modules.Jobs.Infrastructure.Json.Marshaller
    
executables:
  princesa-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - princesa

tests:
  princesa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - princesa
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
