version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-princesa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-princesa}
    ports:
      - "5432:5432"
    restart: unless-stopped
